from langgraph.graph import StateGraph, END

from state import GraphState
from orchestrator.intent_parser import intent_parser
from orchestrator.task_planner import task_planner
from orchestrator.aggregator import aggregator

from agents.fraud_agent import fraud_agent
from agents.risk_agent import risk_agent
from agents.compliance_agent import compliance_agent
from agents.advisory_agent import advisory_agent


def route_agents(state: dict):
    """
    Router function for LangGraph conditional edge.
    Reads the plan generated by the Task Planner and returns a list of target node names.
    LangGraph natively executes the returned list of nodes in parallel.
    """
    plan = state.get("plan", {})
    agents = plan.get("agents", ["advisory"])
    return agents


def build_graph():
    builder = StateGraph(GraphState)
    builder.add_node("intent", intent_parser)
    builder.add_node("plan", task_planner)
    builder.add_node("fraud", fraud_agent)
    builder.add_node("risk", risk_agent)
    builder.add_node("compliance", compliance_agent)
    builder.add_node("advisory", advisory_agent)
    builder.add_node("aggregate", aggregator)
    builder.set_entry_point("intent")
    builder.add_edge("intent", "plan")
    builder.add_conditional_edges("plan", route_agents)
    builder.add_edge("fraud", "aggregate")
    builder.add_edge("risk", "aggregate")
    builder.add_edge("compliance", "aggregate")
    builder.add_edge("advisory", "aggregate")
    builder.add_edge("aggregate", END)

    return builder.compile()